const constants = {
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    APPLIED_FILTERS: 'APPLIED_FILTERS',
    MOVE_TO_CART: 'MOVE_TO_CART',
    RESET_PRODUCTS: 'RESET_PRODUCTS',
    RESET_WISHLIST: 'RESET_WISHLIST',
    RESET_CART: 'RESET_CART',
    SET_ORIGINAL_ITEMS: 'SET_ORIGINAL_ITEMS'
};
export default constants;